# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 19:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelbuddy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='travel_from_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 23, 11, 45, 15, 243000)),
        ),
    ]
